# Generated by Django 5.1.5 on 2025-01-25 14:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.IntegerField(validators=[django.core.validators.MinValueValidator(limit_value=1, message='Номер стола должен быть больше или равен 1')], verbose_name='Номер стола')),
                ('items', models.JSONField(default=list, verbose_name='Список блюд с ценами')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=10, verbose_name='Общая стоимость заказа')),
                ('status', models.CharField(choices=[('waiting', 'В ожидании'), ('ready', 'Готов'), ('paid', 'Оплачено')], default='waiting', max_length=10, verbose_name='Статус заказа')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=8, unique=True, verbose_name=' Уникальный идентификационный номер')),
                ('password', models.CharField(max_length=20, verbose_name='Пароль')),
            ],
            options={
                'verbose_name': 'Работник',
                'verbose_name_plural': 'Работники',
            },
        ),
    ]
